#!/usr/bin/env bash
#displays To infinity and beyond indefinitely
echo "$BASHPID" >> /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'" SIGTERM
trap "rm /var/run/holbertonscript.pid | exit" SIGQUIT & SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
while 'true'
do
echo "To infinity and beyond"
sleep 2
done
