#!/usr/bin/env bash
# This script is displaying numbers from 1 to 100 FizzBuzz
i="1"
while [ $i -le 100 ]
do
	if (! ((i % 3)) ) && (! ((i % 5)) ) ; then
		echo "FizzBuzz"
	elif ! ((i % 5 )); then
		echo "Buzz"
	elif ! ((i % 3)); then
		echo "Fizz"
	else
		echo "$i"
	fi;
i=$((i+1))
done
