#!/usr/bin/env bash
# This script is displaying the content of the file /etc/passwd
while IFS=: read -r user pswd uid guid info home bin
do
echo "The user $user is part of the $guid gang, lives in $home and rides $bin. $uid's place is protected by the passcode $pswd, more info about the user here: $info"
done </etc/passwd
