#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
h="0"
m="1"
while [ $h -le 12 ]
do
	echo "Hour: $h"
	m="0"
        h=$(($h+1))
	while [ $m -le 59 ]
	do
		echo "$m"
		m=$(($m+1))
	done
done
