#!/usr/bin/env bash
# This script is displaying information about the holbertonschool file
if test -e "holbertonschool"; then
	echo "holbertonschool file exists"
	if [ -s "holbertonschool" ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if test -f "holbertonschool";then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
